# yml 파일 작성 시, 들여쓰기 주의!!!
# yml 파일은 하나의 Workflow를 의미합니다.
# name은 workflow의 이름입니다.
name: Github Actions 실행시켜보기

# Event : 언제 workflow를 실행시키고 싶은지 결정하는 부분
# 즉 master branch에 push가 되었을 때, 실행한다는 의미입니다.
on:
  push:
    branches:
      - master
      
# 어떤 실행을 할지 결정하는 부분
# 하나의 Workflow는 1개 이상의 Job으로 구성됩니다.
# 여러 Job은 기본적으로 병렬적으로 수행됩니다.
jobs:
  # My-Deploy-Job은 Job을 식별하기 위한 id
  My-Deploy-Job:
    # ubuntu 환경 / 가장 최신 버전(latest)
    runs-on: ubuntu-latest

    # Step : 특정 작업을 수행하는 가장 작은 단위
    # Job은 여러 Step들로 구성되어 있다.
    # Step 마다 name을 붙일 수 있고, 리눅스 명령어를 사용
    steps:
      - name: Hello World 찍기
        run: echo "Hello World"

      - name: 여러 명령어 문장 작성하기
        run: |
          echo "Good moring"
          echo "bye bye"

      # _SHA에서 반환되는 값은 노출이 되면 안되는 값이므로
      # Sceret 
      - name: Github Actions 자체에 저장되어 있는 변수 사용해보기
        run: |
          echo $GITHUB_SHA
          echo $GITHUB_REPOSITORY

      - name: 아무한테 노출이 되면 안되는 값
        run: |
          echo ${{ secrets.MY_NAME }}
          echo ${{ secrets.MY_HOBBY }}



